name: Build and publish

on:
  push:

jobs:
  build:
    name: Build Wheel and SDist
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.baipp.outputs.package_version }}
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - uses: hynek/build-and-inspect-python-package@v2
      id: baipp

  publish:
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    environment:
      name: publishing
      url: https://pypi.org/project/tap-planetscaleapi/${{ needs.build.outputs.version }}
    needs: build
    permissions:
      contents: write
      id-token: write

    steps:
    - uses: actions/download-artifact@v5
      with:
        name: Packages
        path: dist
    - uses: svenstaro/upload-release-action@v2
      with:
        file: dist/*.whl
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
    - uses: pypa/gh-action-pypi-publish@v1.13.0
