name: Build and publish

on:
  push:

jobs:
  build:
    name: Build Wheel and SDist
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.baipp.outputs.package_version }}
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 0
    - uses: hynek/build-and-inspect-python-package@c52c3a4710070b50470d903818a7b25115dcd076 # v2.13.0
      id: baipp

  publish:
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    environment:
      name: publishing
      url: https://pypi.org/project/tap-planetscaleapi/${{ needs.build.outputs.version }}
    needs: build
    permissions:
      contents: write
      id-token: write

    steps:
    - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: Packages
        path: dist
    - uses: svenstaro/upload-release-action@7027b7670c56b9473901daad1fb8a09ab534688e # latest
      with:
        file: dist/*.whl
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
    - uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
