### A CI workflow template that runs linting and python testing

name: Test tap-planetscaleapi

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths:
    - .github/workflows/test.yml
    - tap_planetscaleapi/**
    - tests/**
    - pyproject.toml
    - tox.ini
    - uv.lock
  pull_request:
    branches: [main]
    paths:
    - .github/workflows/test.yml
    - tap_planetscaleapi/**
    - tests/**
    - pyproject.toml
    - tox.ini
    - uv.lock
  schedule:
  - cron: "0 10 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"
  # renovate: datasource=pypi depName=uv
  UV_VERSION: 0.11.32

jobs:
  pytest:
    name: CI
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        python-version:
        - "3.12"
        - "3.13"
        - "3.14"
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        version: ${{ env.UV_VERSION }}
    - name: Test with pytest
      env:
        TAP_PLANETSCALEAPI_SERVICE_TOKEN_ID: ${{ secrets.TAP_PLANETSCALEAPI_SERVICE_TOKEN_ID }}
        TAP_PLANETSCALEAPI_SERVICE_TOKEN: ${{ secrets.TAP_PLANETSCALEAPI_SERVICE_TOKEN }}
      run: |
        uv run pytest
    - name: Static type checking
      run: |
        uv run mypy tap_planetscaleapi tests
        uv run ty check tap_planetscaleapi tests
